// Smart tags & auto-linking helpers.
// Tags are already generated by AI (see ai.functions.ts) and stored on each
// LocalNote as `tags: string[]`. These helpers surface them in the UI:
//   - topTags: most-used tags across the vault (for filter chips)
//   - relatedNotes: notes similar to a given note by shared tags + media type
import type { LocalNote } from "@/lib/local-db";

export type NoteLike = Pick<LocalNote, "id" | "tags" | "heading" | "created_at"> & {
  media?: LocalNote["media"];
};

export function noteTags(n: NoteLike | null | undefined): string[] {
  if (!n) return [];
  const arr = Array.isArray(n.tags) ? n.tags : [];
  return arr.filter((t): t is string => typeof t === "string" && t.length > 0);
}

/** Most common tags across the vault, sorted by frequency. */
export function topTags(notes: NoteLike[] | null | undefined, limit = 12): { tag: string; count: number }[] {
  if (!notes) return [];
  const counts = new Map<string, number>();
  for (const n of notes) {
    for (const t of noteTags(n)) {
      counts.set(t, (counts.get(t) ?? 0) + 1);
    }
  }
  return Array.from(counts.entries())
    .filter(([, c]) => c >= 2) // suppress one-offs so the pill row is useful
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, limit)
    .map(([tag, count]) => ({ tag, count }));
}

/** Filter notes by a single tag. */
export function notesWithTag<T extends NoteLike>(notes: T[], tag: string): T[] {
  return notes.filter((n) => noteTags(n).includes(tag));
}

/**
 * Rank notes by similarity to `source`. Score = shared-tag count (Jaccard-ish)
 * with a small bonus for same media type. Excludes the source note itself.
 */
export function relatedNotes<T extends NoteLike>(
  source: NoteLike,
  all: T[],
  limit = 6,
): Array<T & { _score: number; _shared: string[] }> {
  const src = new Set(noteTags(source));
  if (src.size === 0) return [];
  const srcMediaType = source.media?.type ?? null;
  const scored: Array<T & { _score: number; _shared: string[] }> = [];
  for (const n of all) {
    if (n.id === source.id) continue;
    const other = noteTags(n);
    if (other.length === 0) continue;
    const shared: string[] = [];
    for (const t of other) if (src.has(t)) shared.push(t);
    if (shared.length === 0) continue;
    const union = src.size + other.length - shared.length;
    const jaccard = shared.length / Math.max(union, 1);
    // Weight raw overlap heavily, add jaccard for tie-breaks, media bonus tiny.
    let score = shared.length * 10 + jaccard * 2;
    if (srcMediaType && n.media?.type === srcMediaType) score += 0.5;
    scored.push({ ...n, _score: score, _shared: shared });
  }
  scored.sort((a, b) => b._score - a._score || (a.created_at < b.created_at ? 1 : -1));
  return scored.slice(0, limit);
}

/** Human-friendly tag label: "kebab-case" → "Kebab case". */
export function prettyTag(tag: string): string {
  const s = tag.replace(/[-_]+/g, " ").trim();
  return s.charAt(0).toUpperCase() + s.slice(1);
}
