/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYoutubeCardTestRouteImport } from './routes/_authenticated/youtube-card-test'
import { Route as AuthenticatedShareRouteImport } from './routes/_authenticated/share'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks.index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections.index'
import { Route as AuthenticatedTasksReviewRouteImport } from './routes/_authenticated/tasks.review'
import { Route as AuthenticatedProfileTrashRouteImport } from './routes/_authenticated/profile_.trash'
import { Route as AuthenticatedNotesIdRouteImport } from './routes/_authenticated/notes.$id'
import { Route as AuthenticatedCollectionsIdRouteImport } from './routes/_authenticated/collections.$id'
import { Route as AuthenticatedCastPersonIdRouteImport } from './routes/_authenticated/cast.$personId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYoutubeCardTestRoute =
  AuthenticatedYoutubeCardTestRouteImport.update({
    id: '/youtube-card-test',
    path: '/youtube-card-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShareRoute = AuthenticatedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksReviewRoute =
  AuthenticatedTasksReviewRouteImport.update({
    id: '/tasks/review',
    path: '/tasks/review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileTrashRoute =
  AuthenticatedProfileTrashRouteImport.update({
    id: '/profile_/trash',
    path: '/profile/trash',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIdRoute = AuthenticatedNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsIdRoute =
  AuthenticatedCollectionsIdRouteImport.update({
    id: '/collections/$id',
    path: '/collections/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCastPersonIdRoute =
  AuthenticatedCastPersonIdRouteImport.update({
    id: '/cast/$personId',
    path: '/cast/$personId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share': typeof AuthenticatedShareRoute
  '/youtube-card-test': typeof AuthenticatedYoutubeCardTestRoute
  '/cast/$personId': typeof AuthenticatedCastPersonIdRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/profile/trash': typeof AuthenticatedProfileTrashRoute
  '/tasks/review': typeof AuthenticatedTasksReviewRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/share': typeof AuthenticatedShareRoute
  '/youtube-card-test': typeof AuthenticatedYoutubeCardTestRoute
  '/cast/$personId': typeof AuthenticatedCastPersonIdRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/profile/trash': typeof AuthenticatedProfileTrashRoute
  '/tasks/review': typeof AuthenticatedTasksReviewRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/share': typeof AuthenticatedShareRoute
  '/_authenticated/youtube-card-test': typeof AuthenticatedYoutubeCardTestRoute
  '/_authenticated/cast/$personId': typeof AuthenticatedCastPersonIdRoute
  '/_authenticated/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/_authenticated/notes/$id': typeof AuthenticatedNotesIdRoute
  '/_authenticated/profile_/trash': typeof AuthenticatedProfileTrashRoute
  '/_authenticated/tasks/review': typeof AuthenticatedTasksReviewRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/search'
    | '/share'
    | '/youtube-card-test'
    | '/cast/$personId'
    | '/collections/$id'
    | '/notes/$id'
    | '/profile/trash'
    | '/tasks/review'
    | '/collections/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/search'
    | '/share'
    | '/youtube-card-test'
    | '/cast/$personId'
    | '/collections/$id'
    | '/notes/$id'
    | '/profile/trash'
    | '/tasks/review'
    | '/collections'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/share'
    | '/_authenticated/youtube-card-test'
    | '/_authenticated/cast/$personId'
    | '/_authenticated/collections/$id'
    | '/_authenticated/notes/$id'
    | '/_authenticated/profile_/trash'
    | '/_authenticated/tasks/review'
    | '/_authenticated/collections/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/youtube-card-test': {
      id: '/_authenticated/youtube-card-test'
      path: '/youtube-card-test'
      fullPath: '/youtube-card-test'
      preLoaderRoute: typeof AuthenticatedYoutubeCardTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/share': {
      id: '/_authenticated/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthenticatedShareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/review': {
      id: '/_authenticated/tasks/review'
      path: '/tasks/review'
      fullPath: '/tasks/review'
      preLoaderRoute: typeof AuthenticatedTasksReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile_/trash': {
      id: '/_authenticated/profile_/trash'
      path: '/profile/trash'
      fullPath: '/profile/trash'
      preLoaderRoute: typeof AuthenticatedProfileTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$id': {
      id: '/_authenticated/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof AuthenticatedNotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections/$id': {
      id: '/_authenticated/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cast/$personId': {
      id: '/_authenticated/cast/$personId'
      path: '/cast/$personId'
      fullPath: '/cast/$personId'
      preLoaderRoute: typeof AuthenticatedCastPersonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedShareRoute: typeof AuthenticatedShareRoute
  AuthenticatedYoutubeCardTestRoute: typeof AuthenticatedYoutubeCardTestRoute
  AuthenticatedCastPersonIdRoute: typeof AuthenticatedCastPersonIdRoute
  AuthenticatedCollectionsIdRoute: typeof AuthenticatedCollectionsIdRoute
  AuthenticatedNotesIdRoute: typeof AuthenticatedNotesIdRoute
  AuthenticatedProfileTrashRoute: typeof AuthenticatedProfileTrashRoute
  AuthenticatedTasksReviewRoute: typeof AuthenticatedTasksReviewRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedShareRoute: AuthenticatedShareRoute,
  AuthenticatedYoutubeCardTestRoute: AuthenticatedYoutubeCardTestRoute,
  AuthenticatedCastPersonIdRoute: AuthenticatedCastPersonIdRoute,
  AuthenticatedCollectionsIdRoute: AuthenticatedCollectionsIdRoute,
  AuthenticatedNotesIdRoute: AuthenticatedNotesIdRoute,
  AuthenticatedProfileTrashRoute: AuthenticatedProfileTrashRoute,
  AuthenticatedTasksReviewRoute: AuthenticatedTasksReviewRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
